### ISSUE TITLE
Bug: browser back from detail never restores home (history says home, DOM stuck on detail)

### ISSUE THREAD

**Issue by NurvX** [NurvX/NuvioWeb#40]
## What breaks

Back-to-home never restores home. Home → detail (any normal movie card) → browser back: history ends at `{route: home}` but the DOM shows the detail screen with home emptied (`#home`: `display:none`, 0 children) and detail visible. The user is stranded — a second back does not recover.

## Repro (production, signed in, 4x CPU throttle, mobile viewport)

1. Load home (521+ posters render).
2. Tap a normal movie poster (Mayday) → detail mounts (~500-750ms).
3. Browser back → after 6-10s: `history.state.route === "home"`, but `#home` hidden+empty, `#detail` visible with content.

Reproduced on both the pre-transition-host bundle and the current `main` bundle (with `screenTransition.js`), so it predates the polish work. Synthetic and trusted back navigation both fail identically.

## Console trail

- `Failed to capture route state detail: this.captureDetailFocus is not a function` (warn, caught)
- `Unhandled promise rejection: this.cancelPendingEpisodeHold is not a function` (unhandled, recurs)
- No `[router-perf] navigate` completion log for the home leg despite history advancing — the swap aborts mid-flight, consistent with detail cleanup throwing inside the atomic DOM swap (or the popstate window swallowing it; needs diagnosis).

## Blocks

#39 (home back-navigation verdict) — restore-vs-keep-alive is unmeasurable while restore itself fails. The measurement checklist on #33 stays valid once this is fixed.

## Notes

Found while measuring #39 under 4x CPU throttle against production with a signed-in session. Not caused by #35/#37/#38 (reproduces without them).

**Comment by NurvX** [comment]
## Resolution

Root cause: detail cleanup called methods from a deleted hold-to-preview feature that no longer exist (cancelPendingEpisodeHold/Season/Poster/HeroHold, destroyDetailHoldDialog, stopEpisodeHoldRepeat, captureDetailFocus). The first throw aborted the atomic DOM swap mid-flight: history advanced to home while the DOM stayed on an emptied detail. Fixed in 302096e (optional calls at the dead sites + warn-and-continue cleanup guard in the navigation host). Verified: harness loop FAIL->PASS, production back-nav PASS 2/2 cycles. Regression: runScreenCleanup unit tests (12 green in screenTransition.test.mjs); router-level test impossible in node (screen graph imports .jsx) — documented, harness loop covers the wiring.
